---
- name: install db
  hosts: all
  become: yes
  gather_facts: False
  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

  - name: Run the equivalent of "apt-get update" as a separate step
    apt:
      update_cache: yes
  - name: Add APT key
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: EA312927

  - name: repo
    apt_repository:
      repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
      state: present

  - name: install db
    apt:
      name: mongodb-org
      state: present
      allow_unauthenticated: yes

  - name: Configure service supervisor
    systemd:
      name: mongod
      enabled: yes
